### ISSUE TITLE
exception nothrow warning

### ISSUE THREAD

**Issue by martinjrobins** [OxfordRSE/template-project-cpp#9] opened 2018-05-09 13:38 UTC
travis says (for both gcc and clang):
```
/home/travis/build/OxfordRSE/template-project-cpp/src/MyLibrary.cpp:44:11: warning: thrown exception type is not nothrow copy constructible [cert-err60-cpp]
    throw std::out_of_range("non-negative argument required");
```

This doesn't seem like a valid warning, since we are just using a standard library exception! Not sure how to fix this

**Comment by fcooper8472** [comment] 2018-05-09 17:41
I have tracked down the clang-tidy warning, which is explained in detail [here](https://wiki.sei.cmu.edu/confluence/display/cplusplus/ERR60-CPP.+Exception+objects+must+be+nothrow+copy+constructible).

I have been unable to reproduce the warning on my machine with the same clang-tidy version, so assume perhaps that newer standard library implementations are now compliant.

I did also find a pretty stale [issue](https://cplusplus.github.io/LWG/issue254) relating to this.

In any case the proposed resolution is to use a `std::runtime_error`; perhaps [`std::range_error`](http://en.cppreference.com/w/cpp/error/range_error) would fit the bill.  What do you think @martinjrobins?

**Comment by martinjrobins** [comment] 2018-05-09 17:50
Yea, swap to `std::range_error` for now. Might have to revisit this in the future, as `std::out_of_range` seems like a better fit based on its description. Why isn't `std::out_of_range` derived from `std::runtime_error` anyway? All exceptions are thrown at run time....

**Comment by fcooper8472** [comment] 2018-05-09 18:05
Yeah, I'm not too sure what the "correct" answer is here.  Should it even be an exception?  It's not necessarily an "exceptional" circumstance for someone to pass in an n too large.

For instance, maths error handling is done differently in the std library:
http://en.cppreference.com/w/cpp/numeric/math/math_errhandling

**Comment by fcooper8472** [comment] 2018-05-09 18:56
And, it looks as though `std::out_of_range` is expected to be used if accessing out-of-range elements, so can be thrown from things like `std::vector::at`.

**Comment by martinjrobins** [comment] 2018-05-09 19:22
so how does `std::vector::at` throw `std::out_of_range`?  It must do it in a certain way that doesn't trigger the warning.

**Comment by fcooper8472** [comment] 2018-05-09 19:40
I think this specific warning is a pedantic one from the CERT Secure Coding Guidelines in clang-tidy - so, perhaps, with the same standard library version the warning would be emitted if clang-tidy was run over the code.

I've been reading the core guidelines and this one in particular is relevant:
http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#e14-use-purpose-designed-user-defined-types-as-exceptions-not-built-in-types

I think we ought to be making ourselves a lightweight exception derived from `std::runtime_error`.

**Comment by fcooper8472** [comment] 2018-05-09 21:50
This ought to fix it: a new
```cpp
class Exception : public std::runtime_error
```
Seems somewhat overkill, but probably good to follow the core guidelines.

Happy to name it something other than `Exception` if you like, although unless we have a need to emit multiple exception types and distinguish between them I think we should keep things fairly straightforward.

**Comment by fcooper8472** [comment] 2018-05-09 22:13
Ok, the travis builds are still spitting out the same warnings with the new Exception class.

[Doing some digging](https://godbolt.org/g/Yiw26b) it looks as though GCC 4.x regards both `std::logic_error` and `std::runtime_error` as NOT nothrow copy constructible, whereas from GCC 5.x onward (and clang) the behaviour seems to be as expected.

Can the version of GCC be bumped up to 5.x on travis @martinjrobins?

**Comment by martinjrobins** [comment] 2018-05-10 06:04
clang still giving similar warnings, although these are not for the copy constructor of the exception class

**Comment by martinjrobins** [comment] 2018-05-10 07:12
ok, that seemed to do the trick, no more exception warnings

**Comment by fcooper8472** [comment] 2018-05-10 11:14
I'm a little uneasy about this fix - if we threw a `runtime_error` instead of our `Exception` we would still see the warning.

The `Exception` class was a carbon copy (after weeding out the macros) of the GCC `range_error` implementation, which would also emit the warnings.
So if there aren't any warnings now, I suspect it's only because the static analyser isn't finding the same problem.

@martinjrobins do you know if there's any way to determine which version of the standard library is being used? Is it definitely the same as the compiler version?

If you look at this example on [godbolt](https://godbolt.org/g/rLwbqR), the `is_nothrow_copy_constructible` is returning `true` on GCC 5.x, but `false` on GCC 4.x (and true on all versions of clang that know about `range_error`.

I just have a hunch that somehow the `g++ (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4` that shows up in the build logs is still working its way in...

**Comment by fcooper8472** [comment] 2018-05-10 11:26
As expected, the configuration on travis thinks the `runtime_error` classes are not nothrow copy constructible, and suspect they are using an older standard library implementation.

Not sure how to proceed though.

**Comment by fcooper8472** [comment] 2018-05-10 11:28
I think we need to figure out why the build outputs both have the following:
```bash
$ export CXX=g++
$ export CC=gcc
$ g++ --version
g++ (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4
```
after the environment variables are set from the travis yaml file...

**Comment by fcooper8472** [comment] 2018-05-10 13:03
Digging some more has revealed that some builds (e.g. [this one](https://travis-ci.org/OxfordRSE/template-project-cpp/jobs/377265230)) are linking against
```
libstdc++.so.6.0.25  (ships with GCC 8.0.0)
```
and others (e.g. [this one](https://travis-ci.org/OxfordRSE/template-project-cpp/jobs/377265231)) are linking against
```
libstdc++.so.6.0.19  (ships with GCC 4.8.3)
``` 
Both builds, however, fail the test, which still leaves me not understanding why the tests pass on my laptop but not on Travis!

**Comment by fcooper8472** [comment] 2018-05-10 14:24
For now, I have turned off the specific warning (`cert-err60-cpp`), as I can only reproduce it within the Travis environment and seems unrelated to the compiler version and the libstdc++ version.

Closing for now.
Perhaps this can be revisited if/when Travis allows us to use Xenial (or Bionic).

**Closed as completed by fcooper8472** 2018-05-10 14:24 UTC

**Comment by fcooper8472** [comment] 2018-05-10 20:37
In case someone on stackoverflow can come up with something, here's a link to the question I have posted:

https://stackoverflow.com/questions/50281098/what-determines-whether-runtime-error-is-nothrow-copy-constructible

**Comment by fcooper8472** [comment] 2018-05-10 22:48
A relevant comment from the stackoverflow question is that this problem has cropped up elsewhere, see for instance:
https://github.com/nlohmann/json/commit/cf7786887c7ca80d86112f6b9f0aeba8cb1f2f9c

>We now only demand our exceptions to be is_nothrow_copy_constructible
>if std::runtime_exception is.

It looks as though there is a growing consensus that this is a warning we should be happy to ignore.

**Comment by martinjrobins** [comment] 2018-05-11 05:12
Ok, well I'm happy to ignore the warning and keep things as they are. What is the reasoning behind overriding the destructor? I'm unsure why this is neccessary

```cpp
 ~Exception() noexcept override = default;
```

**Comment by fcooper8472** [comment] 2018-05-15 16:00
Forgot to reply to this.

It's virtual in the base class, so the derived class ought to have a virtual destructor too.
If it's got a virtual destructor, then `clang-tidy` complains if it's marked `virtual` instead of `override`.

Marking as `override` I can see being useful, because it would ensure that the base class definitely has a virtual destructor.   I think the word `override` is confusing here because you're not literally overriding the base destructor; they destructors in the hierarchy are all called in order.

**Comment by fcooper8472** [comment] 2018-05-17 11:21
As discussed we can, of course, just remove the destructor entirely.

**Comment by martinjrobins** [comment] 2018-05-17 11:29
yea, I think this looks nicer. Happy to keep this.
